server:
  port: 8020
  servlet:
    context-path: /ew-server

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ew_server?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 111777
  mail:
    # 163邮箱的地址为smtp.163.com
    host: smtp.163.com
    # 163邮箱
    username: easywork23@163.com
    # 密码是在开启smtp/pop3时自动生成的
    password: SUSTRPCRXGAHYOQG
#  freemarker:
#    charset: UTF-8
#    request-context-attribute: request
#    settings:
#      number_format: 0.##########
#    suffix: .ftl
#    templateLoaderPath: classpath:/templates/
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: classpath:/static/
sso:
  redis:
    address: redis://127.0.0.1:6379
    expire:
      minute: 720
  #  注销登陆path，值为Client端应用的相对路径
  logout:
    path: /logout
  # SSO Server认证中心地址
  server: http://127.0.0.1:8080/ew-server
  #  路径排除Path，允许设置多个，且支持Ant表达式。用于排除SSO客户端不需要过滤的路径
  excluded:
    paths: /doLogin,/login,/user/register/*

mybatis-plus:
  configuration:
    # 打印日志，会显示实际执行的SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aliyun:
  oss:
    file:
      endpoint: https://oss-cn-shenzhen.aliyuncs.com
      keyid: LTAI5tSEjsfbE1pdCGgibCC7 # 秘钥值
      keysecret: 2fX2KNQfGiE73FofyvH7blplzXPart # 秘钥偏移量
      bucketname: easywork23 # bucket的名字