server:
  port: 8022
  servlet:
    context-path: /api/ew-project
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easy_work?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 111777
  # 应用名称
  application:
    name: ew-chat
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848

sso:
  redis:
    address: redis://127.0.0.1:6379
    expire:
      minute: 720
  #  注销登陆path，值为Client端应用的相对路径
  logout:
    path: /logout
  # SSO Server认证中心地址
  server: http://127.0.0.1:8020/ew-server
  #  路径排除Path，允许设置多个，且支持Ant表达式。用于排除SSO客户端不需要过滤的路径
  excluded:
    paths:

mybatis-plus:
  configuration:
    # 打印日志，会显示实际执行的SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
