server:
  port: 8020
  servlet:
    context-path: /sso-server
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easy_work?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 111777
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: classpath:/static/
sso:
  redis:
    address: redis://127.0.0.1:6379
    expire:
      minute: 60
mybatis-plus:
  configuration:
    # 打印日志，会显示实际执行的SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl